### ISSUE TITLE
Last release lacks APK file

### ISSUE THREAD

**Issue by IzzySoft** [nvv/Far-On-Droid#2]
Or is there none for v0.8.4.2? What went to Playstore then? ;)

Maybe you could add the `.apk` to the v0.8.4.2 release? Thanks!

**Comment by IzzySoft** [comment]
Thanks a lot! Just grabbed v0.8.4.3 :)

**Comment by nvv** [comment]
Hi,

I must be missed your original email, sorry. anyways, you can grab apk
directly from Google Play :)

On Thu, Jun 9, 2016 at 12:37 AM, Izzy notifications@github.com wrote:

> Thanks a lot! Just grabbed v0.8.4.3 :)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/nvv/Far-On-Droid/issues/2#issuecomment-224736930, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABdq00zlhn4o9jNT0qwoZbPPcw_X7DJfks5qJzYrgaJpZM4Il2Py
> .

## 

Regards
Vlad Namashko

**Comment by IzzySoft** [comment]
> anyways, you can grab apk directly from Google Play

Not on Android devices without GApps and without Google account :) Pointer: [Android without Google: microG](https://android.izzysoft.de/articles/named/android-without-google-5a) More and more privacy aware Android users chose this way. So we use other sources, such as F-Droid – and repositories compatible with the F-Droid client, see [Inofficial (and incomplete) list of F-Droid repositories](https://android.izzysoft.de/articles/named/list-of-fdroid-repos). And in case you already hear some bell ringing: yes, [here it is](https://android.izzysoft.de/repo/apk/com.openfarmanager.android) – including auto-updates for all those on the same road. My way as non-dev to support both ends (developers and users) :smiley_cat:

**Comment by nvv** [comment]
Hm, interesting :)

Anyways, you can download apk from G Play on PC with things like this:

https://apps.evozi.com/apk-downloader/

On Thu, Jun 9, 2016 at 9:51 PM, Izzy notifications@github.com wrote:

> anyways, you can grab apk directly from Google Play
> 
> Not on Android devices without GApps and without Google account :)
> Pointer: Android without Google: microG
> https://android.izzysoft.de/articles/named/android-without-google-5a
> More and more privacy aware Android users chose this way. So we use other
> sources, such as F-Droid – and repositories compatible with the F-Droid
> client, see Inofficial (and incomplete) list of F-Droid repositories
> https://android.izzysoft.de/articles/named/list-of-fdroid-repos. And in
> case you already hear some bell ringing: yes, here it is
> https://android.izzysoft.de/repo/apk/com.openfarmanager.android –
> including auto-updates for all those on the same road. My way as non-dev to
> support both ends (developers and users) 😺
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/nvv/Far-On-Droid/issues/2#issuecomment-224991071, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABdq0-7SpgCdmoZVRaJ2DV3WbfFv_oHWks5qKGDEgaJpZM4Il2Py
> .

## 

Regards
Vlad Namashko

**Comment by IzzySoft** [comment]
Yes. You and me, we could do that maybe. Not everyone can. Plus it would require checking for updates manually. From Github `release/` pages, my script can do that automatically: within 24h after you've released a new version and attached the `.apk`, it's available in my repo. As soon as clients refreshed their libraries, it shows up for the user: "New update available for Far-On-Droid". Much more convenient – and no fiddling with all kind of tools. When we said Good-Bye to GApps we didn't mean to make our lifes as complicated as possible – we still have most of the conveniences, but we have them in our hands and under our control ;)

**Comment by nvv** [comment]
Ah, I see :) Then, good luck with your project!

On Thu, Jun 9, 2016 at 10:17 PM, Izzy notifications@github.com wrote:

> Yes. You and me, we could do that maybe. Not everyone can. Plus it would
> require checking for updates manually. From Github release/ pages, my
> script can do that automatically: within 24h after you've released a new
> version and attached the .apk, it's available in my repo. As soon as
> clients refreshed their libraries, it shows up for the user: "New update
> available for Far-On-Droid". Much more convenient – and no fiddling with
> all kind of tools. When we said Good-Bye to GApps we didn't mean to make
> our lifes as complicated as possible – we still have most of the
> conveniences, but we have them in our hands and under our control ;)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/nvv/Far-On-Droid/issues/2#issuecomment-224998038, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABdq05sPpxdWCRig1iDGI0S414oxuGbUks5qKGa6gaJpZM4Il2Py
> .

## 

Regards
Vlad Namashko

**Comment by IzzySoft** [comment]
Thanks a lot! Closing this issue then as it's solved :)
